application: concierge
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: concierge_api.application

- url: /app
  static_dir: app

- url: /.*
  script: concierge_api.redirect

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
