application: concierge
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: concierge_api.api_application

- url: /app
  static_dir: app

- url: /.*
  script: ingest_into_datastore.ingest_application

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
